### PR TITLE
Adding more text statistics

### PR DESCRIPTION
**Pull request by hirschenberger**
Using the excellent 'punkt' crate for language dependent sentence counting. Perhaps adding further *readability* stats like **Flesch reading ease** later.

### CODE REVIEW

**Comment by hirschenberger** [comment]
There seems to be a bug in the `punkt` crate which causes a panic with the crowbook `guide`. I'm working on a PR...

**Comment by hirschenberger** [comment]
The PR for the `punkt` issue: https://github.com/ferristseng/rust-punkt/pull/9

**Comment by lise-henry** [comment]
Thanks for the PR (and the related PR to rust-punkt). I have little time currently but I'll look into this and hopefully integrate it in february :)

**Comment by hirschenberger** [comment]
The PR in `rust-punkt` has landed in crates.io as version 1.0.4. Now the crowbook guide statistics (-S) works.

**Comment by lise-henry** [comment]
Thanks! It doesn't seem to build on stable, but I guess I'll just add a conditional compilation option ASAP

**Pull request merged**
