### PR TITLE
Now you can switch from one chapter view to whole book view and reverse

### PR DESCRIPTION
**Pull request by taophp**

### CODE REVIEW

**Comment by lise-henry** [comment]
Thanks for your contribution! I made some esthetic changes (it felt more logical, at least to me, to have the menu icon and the "book" icon next to each other) and a bit more internal changes. Still working on the pseudo-"internationalisation" part.

**Comment by taophp** [comment]
You're welcome.

> it felt more logical, at least to me, to have the menu icon and the "book" icon next to each other

Well, I tough about this, so let me share my views. The menu icon (hamburger-style) you use _means_ that it hides and shows menus and controls, specially for mobile. So, semantically, the icons should be in the menu, if I understand well the hamburger menu philosophy.
As a reader (and a writer), I like distraction-free interface. So, hide the icon in the retractable menu makes is a good thing for me.

Just my two cents.

**Comment by lise-henry** [comment]
My intent for this icon was to indicate a table of content. The "hamburger" icon is indeed probably an error to convey this meaning, but I still think it makes sense to separate the table of contents from reading settings. Though I agree it could be a bit more discrete. Will look a bit at gitbook/other comparable solutions to see how they do it.

**Comment by lise-henry** [comment]
After toying a bit with it, I moved back to your suggestion. Also (unless you don't want to), should I use "Stéphane Mourey" to add in a "contributors" section? Or you prefer something else ? ^^

**Comment by taophp** [comment]
I will be pleased to see "Stéphane Mourey" in the contributor section. Thanks. Do you mind to add some contact informations like my website http://stephanemourey.fr and this email s+crowbook@stephanemourey.fr ?

**Comment by lise-henry** [comment]
no problem

**Pull request merged**
